# UI Constants
import os

BUTTON_SIZE = 50
ACTION_BUTTON_WIDTH = 80
ACTION_BUTTON_HEIGHT = 40


# Image Directory
IMAGE_DIR = os.path.join(os.getcwd(), "product_images")

# Product Grid Layout
PRODUCTS_PER_ROW = 4
PRODUCT_GRID_SPACING = 12

# Product Button Dimensions
PRODUCT_BUTTON_WIDTH = 120
PRODUCT_BUTTON_HEIGHT = 180
PRODUCT_ICON_SIZE = 100

# Billing Section
BILLING_SECTION_WIDTH = 350

# Font Settings
PRODUCT_BUTTON_FONT_FAMILY = "Arial"
PRODUCT_BUTTON_FONT_SIZE = 18

# Default Category
DEFAULT_CATEGORY = "fruits_veg"
# Title Bar Constants
TITLE_BAR_HEIGHT = 50
TITLE_BAR_MARGIN = 10
TITLE_BAR_SPACING = 10
TITLE_BAR_LEFT_SPACING = 15

# Title Bar Button Dimensions
TITLE_BAR_BUTTON_SIZE = 40
MENU_BUTTON_SIZE = 40
WINDOW_CONTROL_BUTTON_SIZE = 40

# Category Button Dimensions
FRUITS_BUTTON_WIDTH = 120
FRUITS_BUTTON_HEIGHT = 35
MANUAL_BUTTON_WIDTH = 100
MANUAL_BUTTON_HEIGHT = 35

# Barcode Input Dimensions
BARCODE_INPUT_WIDTH = 70
BARCODE_INPUT_HEIGHT = 35

# Font Settings
TITLE_BAR_FONT_FAMILY = "Arial"
TITLE_BAR_FONT_SIZE = 16
MENU_BUTTON_FONT_SIZE = 16
WINDOW_CONTROL_FONT_SIZE = 16
MAXIMIZE_BUTTON_FONT_SIZE = 14

# App Title
APP_TITLE = "FPOS"

# Placeholder Text
BARCODE_PLACEHOLDER = "Scan barcode here..."
